resources:
  repositories:
    - repository: templates
      type: github
      name: bincrafters/templates
      endpoint: github

jobs:
- template: azure-template.yml
  parameters:
    conanLoginUsername: $(CONAN_LOGIN_USERNAME)
    conanPassword: $(CONAN_PASSWORD)
    collectionsBasePath: "recipes"
    conanUploadOnlyWhenStable: "false"
    # collectionsConanfileBasePath: 'recipes\boost_base\'
    collectionsRecipes:
      - name: 'boost_base\all'
      - name: 'boost_callable_traits\all'
      - name: 'boost_compatibility\all'
      - name: 'boost_config\all'
